import:
  - ~/catppuccin/catppuccin-mocha.yml

window:
  padding:
    x: 18
    y: 16
  dynamic padding: false
  decorations: buttonless
  startup_mode: SimpleFullscreen

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italir

  size: 20

key_bindings:
  - { key: J, mods: Command, chars: "\x01v" } # <Ctrl-a>+v - Vertical slice [J]
  - { key: H, mods: Command, chars: "\x01-" } # <Ctrl-a>+- - [H]orizontal slice
  - { key: G, mods: Command, chars: "\x01g" } # <Ctrl-a>+g - Opens lazy[G]it
  - { key: L, mods: Command, chars: "\x01s" } # <Ctrl-a>+s - [L]ist sessions
  - { key: M, mods: Command, chars: "\x01m" } # <Ctrl-a>+m - [M]aximize pane
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" } # <Esc>:w<Enter> - [S]aves vim
  - { key: T, mods: Command, chars: "\x01c" } # <Ctrl-a>+c - [T]o create a new window
  - { key: W, mods: Command, chars: "\x01x" } # <Ctrl-a>+x - To remove a [W]indow
  - { key: Minus, mods: Command, chars: "\x01L" } # <Ctrl-a>+l - previous session
  - { key: Period, mods: Command, chars: "\x01n" } # <Ctrl-a>+n - next window
  - { key: Comma, mods: Command, chars: "\x01p" } # <Ctrl-a>+p - previous window
